title: Jonathan Alvarez - Especialista en Redes y Ciberseguridad
description: Portafolio profesional de Jonathan Alvarez, docente y especialista en redes, ciberseguridad y educación tecnológica
baseurl: "/portafolio_grupo_D_uc/jonathan-alvarez"  
url: "https://digitec-conexion.github.io/portafolio_grupo_D_uc/jonathan-alvarez/" 
remote_theme: pages-themes/hacker@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag # Para mejor SEO
  - jekyll-data # Importante para procesar JSON

defaults:
  - scope:
      path: ""
    values:
      layout: default

sass:
  style: compressed

# Configuración personalizada
social:
  linkedin: jonathan-ac28
  email: jalvarezc@tecsup.edu.pe

data_source: _data
collections:
  data:
    output: true
