title: Jonathan Alvarez - Especialista en Redes y Ciberseguridad
description: Portafolio profesional de Jonathan Alvarez, docente y especialista en redes, ciberseguridad y educación tecnológica

baseurl: "/portafolio_grupo_D_uc/jonathan-alvarez"
url: "https://digitec-conexion.github.io"

remote_theme: pages-themes/hacker@v0.2.0

# Configuración esencial para plugins
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-data
  - jekyll-feed  # Recomendado añadir para RSS

# Configuración de defaults
defaults:
  - scope:
      path: ""  # Todos los archivos
    values:
      layout: default
  - scope:
      path: "data"  # Especifica que los archivos JSON son datos
    values:
      layout: null  # No usar layout para archivos de datos

# Configuración de procesamiento
markdown: kramdown
highlighter: rouge
sass:
  style: compressed

# Configuración de datos

<<<<<<< HEAD
data_source: "data"
collections:
  data:
    output: false
    path: "data"

include:
  - "/data/education.json"
  - "/data/experience.json"
  - "/data/projects.json"
  - "/data/skills.json"
=======
data_dir: "jonathan-alvarez/_data"  # Ruta relativa al repositorio
data_source: "_data"                # Ruta relativa al sitio

# Carga manual de archivos (solución definitiva)
include:
  - "jonathan-alvarez/_data/education.json"
  - "jonathan-alvarez/_data/experience.json"
  - "jonathan-alvarez/_data/projects.json"
  - "jonathan-alvarez/_data/skills.json"

# Configuración adicional
collections:
  data:
    output: false
    permalink: /:path/

>>>>>>> ebe79292fb22254d1e1f12d2b240e796078ef7a3
# Configuración personalizada
social:
  linkedin: jonathan-ac28
  email: jalvarezc@tecsup.edu.pe
  github: jthnconti  # Añadido para enlace a GitHub

# Configuración específica para GitHub Pages
github: [metadata]