title: Jonathan Alvarez - Especialista en Redes y Ciberseguridad
description: Portafolio profesional de Jonathan Alvarez, docente y especialista en redes, ciberseguridad y educación tecnológica
baseurl: "/portafolio_grupo_D_uc/jonathan-alvarez"  
url: "https://digitec-conexion.github.io"  # Cambiado a dominio raíz
remote_theme: pages-themes/hacker@v0.2.0

# Configuración esencial para plugins
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-data
  - jekyll-feed  # Recomendado añadir para RSS

# Configuración de defaults
defaults:
  - scope:
      path: ""  # Todos los archivos
    values:
      layout: default
  - scope:
      path: "_data"  # Especifica que los archivos JSON son datos
    values:
      layout: null  # No usar layout para archivos de datos

# Configuración de procesamiento
markdown: kramdown
highlighter: rouge
sass:
  style: compressed

# Configuración de datos

data_source: ./jonathan-alvarez/_data  # Ruta relativa explícita desde la raíz del repo
collections:
  data:
    output: false
    path: "jonathan-alvarez/_data"  # Ruta absoluta desde la raíz

# Añade esto para asegurar que Jekyll incluya los archivos
include:
  - jonathan-alvarez/_data/education.json
  - jonathan-alvarez/_data/experience.json
  - jonathan-alvarez/_data/projects.json
  - jonathan-alvarez/_data/skills.json

# Configuración personalizada
social:
  linkedin: jonathan-ac28
  email: jalvarezc@tecsup.edu.pe
  github: jthnconti  # Añadido para enlace a GitHub

# Configuración específica para GitHub Pages
github: [metadata]